[tool.poetry]
name = "parlamento"
version = "0.1.0"
description = "Extract information from PPortuguese Parliament API."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.6.1,<4.0"
requests = "^2.25.1"
pandas = "^1.1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
