[tool.poetry]
name = "portuguese_politics"
version = "0.2.0"
description = "Extract information from different sources regarding Portuguese Politics."
authors = ["Luis Silva <luisiul359@gmail.com>"]
packages = [ { include = "parliament" }, { include = "elections" }, { include = "app" } ]

[tool.poetry.dependencies]
python = "3.9.7"
requests = "~2.25.1"
pandas = "~1.1.5"
ipykernel = "~5.5.6"
tqdm = "~4.62.3"
fastapi = "~0.68.2"
uvicorn = {version = "~0.15.0", extras = ["standard"]}
gunicorn = "20.1.0"
APScheduler = "~3.8.1"
rq = "~1.10.0"
psycopg2 = "~2.9.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
